// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.10.0+v0.29.4
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
namespace BABR.BACY;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_bacy_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_bacy_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal readonly struct ForeignBytes {
    public readonly int length;
    public readonly IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
readonly struct UniffiRustCallStatus {
    public readonly sbyte code;
    public readonly RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

public class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

public class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

public class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

public class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

public class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

public class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

public class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: UniffiException
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: UniffiException
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0 && !objType.IsArray) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
             //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
             //for all values as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
             //This extra code tests to not call "Dispose" for a List<int>()
             //for all keys as "int" and alike doesn't support interface "IDisposable"
             var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
             var elementValuesTypeCode = Type.GetTypeCode(elementType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action){
        foreach (var item in items) {
            action(item);
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteBytes(byte[] buffer) {
#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteInt(int value) => stream.WriteInt32(value);

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public ulong ReadULong() => stream.ReadUInt64();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public sbyte ReadSByte() => (sbyte)ReadByte();
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public short ReadShort() => (short)ReadUShort();
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
static partial class _UniFFILib {
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public readonly struct UniffiForeignFuture
    {
        public readonly ulong @handle;
        public readonly IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public readonly struct UniffiForeignFutureStructU8
    {
        public readonly byte @returnValue;
        public readonly UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructPointer
    {
        public IntPtr @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompletePointer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructPointer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructVoid @result
    );










































































































































    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();

        }

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_bacy_fn_func_crc_compare(RustBuffer @path,uint @expectedCrc,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint uniffi_bacy_fn_func_crc_compute_bytes(RustBuffer @buffer,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint uniffi_bacy_fn_func_crc_compute_streaming(RustBuffer @path,ulong @bufferSize,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_crc_evaluate(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_bacy_fn_func_crc_forge(RustBuffer @filePath,uint @targetCrc,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_bacy_fn_func_crc_match_file(RustBuffer @filePath,RustBuffer @targetFilePath,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_get_file_path(RustBuffer @path,RustBuffer @crc,sbyte @noHash,sbyte @toLower,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint uniffi_bacy_fn_func_md5_compute_digest(RustBuffer @source,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ulong uniffi_bacy_fn_func_md5_compute_digest64(RustBuffer @source,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ulong uniffi_bacy_fn_func_md5_compute_digest64_hmac(RustBuffer @source,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint uniffi_bacy_fn_func_md5_compute_digest_hmac(RustBuffer @source,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_md5_compute_hash(RustBuffer @source,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_md5_compute_hash_hmac(RustBuffer @source,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_md5_compute_hash_str(RustBuffer @source,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_md5_compute_hash_str_hmac(RustBuffer @source,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_md5_compute_head(RustBuffer @source,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_md5_to_hex_string(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_table_create_key(RustBuffer @name,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_table_create_password(RustBuffer @key,ulong @length,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial float uniffi_bacy_fn_func_table_decrypt_f32(float @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial double uniffi_bacy_fn_func_table_decrypt_f64(double @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int uniffi_bacy_fn_func_table_decrypt_i32(int @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial long uniffi_bacy_fn_func_table_decrypt_i64(long @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_table_decrypt_string(RustBuffer @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint uniffi_bacy_fn_func_table_decrypt_u32(uint @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ulong uniffi_bacy_fn_func_table_decrypt_u64(ulong @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial float uniffi_bacy_fn_func_table_encrypt_f32(float @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial double uniffi_bacy_fn_func_table_encrypt_f64(double @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_table_encrypt_string(RustBuffer @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_table_xor(RustBuffer @name,RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_xor_encrypt(RustBuffer @data,ulong @offset,ulong @length,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_xor_encrypt_with_key(RustBuffer @data,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_xor_exact(RustBuffer @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_bacy_fn_func_xor_inplace_bytes(RustBuffer @data,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint uniffi_bacy_fn_func_xxhash_calculate_hash(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ulong uniffi_bacy_fn_func_xxhash_calculate_hash64(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ulong uniffi_bacy_fn_func_xxhash_calculate_hash64_str(RustBuffer @s,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint uniffi_bacy_fn_func_xxhash_calculate_hash_str(RustBuffer @s,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial sbyte uniffi_bacy_fn_func_xxhash_get_use_big_endian(ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_bacy_fn_func_xxhash_set_use_big_endian(sbyte @value,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_bacy_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_bacy_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_bacy_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_u8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_u8(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_u8(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial byte ffi_bacy_rust_future_complete_u8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_i8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_i8(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_i8(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial sbyte ffi_bacy_rust_future_complete_i8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_u16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_u16(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_u16(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort ffi_bacy_rust_future_complete_u16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_i16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_i16(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_i16(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial short ffi_bacy_rust_future_complete_i16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_u32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_u32(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_u32(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint ffi_bacy_rust_future_complete_u32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_i32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_i32(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_i32(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int ffi_bacy_rust_future_complete_i32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_u64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_u64(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_u64(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ulong ffi_bacy_rust_future_complete_u64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_i64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_i64(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_i64(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial long ffi_bacy_rust_future_complete_i64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_f32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_f32(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_f32(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial float ffi_bacy_rust_future_complete_f32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_f64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_f64(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_f64(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial double ffi_bacy_rust_future_complete_f64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_pointer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_pointer(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_pointer(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr ffi_bacy_rust_future_complete_pointer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_rust_buffer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_rust_buffer(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_rust_buffer(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_bacy_rust_future_complete_rust_buffer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_poll_void(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_cancel_void(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_free_void(IntPtr @handle
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_bacy_rust_future_complete_void(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_crc_compare(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_crc_compute_bytes(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_crc_compute_streaming(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_crc_evaluate(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_crc_forge(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_crc_match_file(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_get_file_path(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_digest(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_digest64(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_digest64_hmac(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_digest_hmac(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_hash(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_hash_hmac(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_hash_str(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_hash_str_hmac(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_compute_head(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_md5_to_hex_string(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_create_key(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_create_password(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_decrypt_f32(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_decrypt_f64(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_decrypt_i32(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_decrypt_i64(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_decrypt_string(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_decrypt_u32(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_decrypt_u64(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_encrypt_f32(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_encrypt_f64(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_encrypt_string(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_table_xor(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xor_encrypt(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xor_encrypt_with_key(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xor_exact(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xor_inplace_bytes(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xxhash_calculate_hash(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xxhash_calculate_hash64(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xxhash_calculate_hash64_str(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xxhash_calculate_hash_str(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xxhash_get_use_big_endian(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_bacy_checksum_func_xxhash_set_use_big_endian(
    );

    [LibraryImport("bacy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint ffi_bacy_uniffi_contract_version(
    );



    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_bacy_uniffi_contract_version();
        if (29 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"BACY: uniffi bindings expected version `29`, library returned `{scaffolding_contract_version}`");
        }
    }

    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_crc_compare();
            if (checksum != 44870) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_crc_compare` checksum `44870`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_crc_compute_bytes();
            if (checksum != 49463) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_crc_compute_bytes` checksum `49463`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_crc_compute_streaming();
            if (checksum != 25854) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_crc_compute_streaming` checksum `25854`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_crc_evaluate();
            if (checksum != 63571) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_crc_evaluate` checksum `63571`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_crc_forge();
            if (checksum != 18991) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_crc_forge` checksum `18991`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_crc_match_file();
            if (checksum != 47090) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_crc_match_file` checksum `47090`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_get_file_path();
            if (checksum != 62508) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_get_file_path` checksum `62508`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_digest();
            if (checksum != 18222) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_digest` checksum `18222`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_digest64();
            if (checksum != 4724) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_digest64` checksum `4724`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_digest64_hmac();
            if (checksum != 40619) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_digest64_hmac` checksum `40619`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_digest_hmac();
            if (checksum != 25152) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_digest_hmac` checksum `25152`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_hash();
            if (checksum != 44001) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_hash` checksum `44001`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_hash_hmac();
            if (checksum != 40560) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_hash_hmac` checksum `40560`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_hash_str();
            if (checksum != 30646) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_hash_str` checksum `30646`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_hash_str_hmac();
            if (checksum != 41336) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_hash_str_hmac` checksum `41336`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_compute_head();
            if (checksum != 59270) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_compute_head` checksum `59270`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_md5_to_hex_string();
            if (checksum != 27889) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_md5_to_hex_string` checksum `27889`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_create_key();
            if (checksum != 43658) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_create_key` checksum `43658`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_create_password();
            if (checksum != 3702) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_create_password` checksum `3702`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_decrypt_f32();
            if (checksum != 1285) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_decrypt_f32` checksum `1285`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_decrypt_f64();
            if (checksum != 23488) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_decrypt_f64` checksum `23488`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_decrypt_i32();
            if (checksum != 64525) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_decrypt_i32` checksum `64525`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_decrypt_i64();
            if (checksum != 27158) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_decrypt_i64` checksum `27158`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_decrypt_string();
            if (checksum != 21308) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_decrypt_string` checksum `21308`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_decrypt_u32();
            if (checksum != 22816) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_decrypt_u32` checksum `22816`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_decrypt_u64();
            if (checksum != 21478) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_decrypt_u64` checksum `21478`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_encrypt_f32();
            if (checksum != 39482) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_encrypt_f32` checksum `39482`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_encrypt_f64();
            if (checksum != 6128) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_encrypt_f64` checksum `6128`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_encrypt_string();
            if (checksum != 46277) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_encrypt_string` checksum `46277`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_xor();
            if (checksum != 11335) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_xor` checksum `11335`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_encrypt();
            if (checksum != 52074) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_encrypt` checksum `52074`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_encrypt_with_key();
            if (checksum != 28120) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_encrypt_with_key` checksum `28120`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_exact();
            if (checksum != 57851) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_exact` checksum `57851`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_inplace_bytes();
            if (checksum != 10506) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_inplace_bytes` checksum `10506`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xxhash_calculate_hash();
            if (checksum != 16841) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xxhash_calculate_hash` checksum `16841`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xxhash_calculate_hash64();
            if (checksum != 65288) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xxhash_calculate_hash64` checksum `65288`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xxhash_calculate_hash64_str();
            if (checksum != 50001) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xxhash_calculate_hash64_str` checksum `50001`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xxhash_calculate_hash_str();
            if (checksum != 15363) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xxhash_calculate_hash_str` checksum `15363`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xxhash_get_use_big_endian();
            if (checksum != 26720) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xxhash_get_use_big_endian` checksum `26720`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xxhash_set_use_big_endian();
            if (checksum != 26348) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xxhash_set_use_big_endian` checksum `26348`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterUInt32: FfiConverter<uint, uint> {
    public static FfiConverterUInt32 INSTANCE = new FfiConverterUInt32();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override uint Lift(uint value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override uint Read(BigEndianStream stream) {
        return stream.ReadUInt();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override uint Lower(uint value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int AllocationSize(uint value) {
        return 4;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override void Write(uint value, BigEndianStream stream) {
        stream.WriteUInt(value);
    }
}



class FfiConverterInt32: FfiConverter<int, int> {
    public static FfiConverterInt32 INSTANCE = new FfiConverterInt32();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int Lift(int value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int Read(BigEndianStream stream) {
        return stream.ReadInt();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int Lower(int value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int AllocationSize(int value) {
        return 4;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override void Write(int value, BigEndianStream stream) {
        stream.WriteInt(value);
    }
}



class FfiConverterUInt64: FfiConverter<ulong, ulong> {
    public static FfiConverterUInt64 INSTANCE = new FfiConverterUInt64();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override ulong Lift(ulong value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override ulong Read(BigEndianStream stream) {
        return stream.ReadULong();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override ulong Lower(ulong value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int AllocationSize(ulong value) {
        return 8;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override void Write(ulong value, BigEndianStream stream) {
        stream.WriteULong(value);
    }
}



class FfiConverterInt64: FfiConverter<long, long> {
    public static FfiConverterInt64 INSTANCE = new FfiConverterInt64();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override long Lift(long value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override long Read(BigEndianStream stream) {
        return stream.ReadLong();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override long Lower(long value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int AllocationSize(long value) {
        return 8;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override void Write(long value, BigEndianStream stream) {
        stream.WriteLong(value);
    }
}



class FfiConverterFloat: FfiConverter<float, float> {
    public static FfiConverterFloat INSTANCE = new FfiConverterFloat();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override float Lift(float value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override float Read(BigEndianStream stream) {
        return stream.ReadFloat();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override float Lower(float value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int AllocationSize(float value) {
        return 4;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override void Write(float value, BigEndianStream stream) {
        stream.WriteFloat(value);
    }
}



class FfiConverterDouble: FfiConverter<double, double> {
    public static FfiConverterDouble INSTANCE = new FfiConverterDouble();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override double Lift(double value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override double Read(BigEndianStream stream) {
        return stream.ReadDouble();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override double Lower(double value) {
        return value;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int AllocationSize(double value) {
        return 8;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override void Write(double value, BigEndianStream stream) {
        stream.WriteDouble(value);
    }
}



class FfiConverterBoolean: FfiConverter<bool, sbyte> {
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override bool Lift(sbyte value) {
        return value != 0;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override bool Read(BigEndianStream stream) {
        return Lift(stream.ReadSByte());
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override sbyte Lower(bool value) {
        return value ? (sbyte)1 : (sbyte)0;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override int AllocationSize(bool value) {
        return (sbyte)1;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    public override void Write(bool value, BigEndianStream stream) {
        stream.WriteSByte(Lower(value));
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}




class FfiConverterByteArray: FfiConverterRustBuffer<byte[]> {
    public static FfiConverterByteArray INSTANCE = new FfiConverterByteArray();

    public override byte[] Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        return stream.ReadBytes(length);
    }

    public override int AllocationSize(byte[] value) {
        return 4 + value.Length;
    }

    public override void Write(byte[] value, BigEndianStream stream) {
        stream.WriteInt(value.Length);
        stream.WriteBytes(value);
    }
}



public record CrcResult (
    uint @value,
    string @hex
) {
}

class FfiConverterTypeCrcResult: FfiConverterRustBuffer<CrcResult> {
    public static FfiConverterTypeCrcResult INSTANCE = new FfiConverterTypeCrcResult();

    public override CrcResult Read(BigEndianStream stream) {
        return new CrcResult(
            @value: FfiConverterUInt32.INSTANCE.Read(stream),
            @hex: FfiConverterString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(CrcResult value) {
        return 0
            + FfiConverterUInt32.INSTANCE.AllocationSize(value.@value)
            + FfiConverterString.INSTANCE.AllocationSize(value.@hex);
    }

    public override void Write(CrcResult value, BigEndianStream stream) {
            FfiConverterUInt32.INSTANCE.Write(value.@value, stream);
            FfiConverterString.INSTANCE.Write(value.@hex, stream);
    }
}





public class HashException: UniffiException {
    HashException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.

    public class Io: HashException {
        public Io(string message): base(message) {}
    }

    public class InvalidPath: HashException {
        public InvalidPath(string message): base(message) {}
    }

    public class Mismatch: HashException {
        public Mismatch(string message): base(message) {}
    }

}

class FfiConverterTypeHashError : FfiConverterRustBuffer<HashException>, CallStatusErrorHandler<HashException> {
    public static FfiConverterTypeHashError INSTANCE = new FfiConverterTypeHashError();

    public override HashException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new HashException.Io(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new HashException.InvalidPath(FfiConverterString.INSTANCE.Read(stream));
            case 3: return new HashException.Mismatch(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeHashError.Read()", value));
        }
    }

    public override int AllocationSize(HashException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(HashException value, BigEndianStream stream) {
        switch (value) {
            case HashException.Io:
                stream.WriteInt(1);
                break;
            case HashException.InvalidPath:
                stream.WriteInt(2);
                break;
            case HashException.Mismatch:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeHashError.Write()", value));
        }
    }
}





public class TableEncryptionException: UniffiException {
    TableEncryptionException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.

    public class Base64Decode: TableEncryptionException {
        public Base64Decode(string message): base(message) {}
    }

    public class StringConversionFailed: TableEncryptionException {
        public StringConversionFailed(string message): base(message) {}
    }

}

class FfiConverterTypeTableEncryptionError : FfiConverterRustBuffer<TableEncryptionException>, CallStatusErrorHandler<TableEncryptionException> {
    public static FfiConverterTypeTableEncryptionError INSTANCE = new FfiConverterTypeTableEncryptionError();

    public override TableEncryptionException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new TableEncryptionException.Base64Decode(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new TableEncryptionException.StringConversionFailed(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTableEncryptionError.Read()", value));
        }
    }

    public override int AllocationSize(TableEncryptionException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(TableEncryptionException value, BigEndianStream stream) {
        switch (value) {
            case TableEncryptionException.Base64Decode:
                stream.WriteInt(1);
                break;
            case TableEncryptionException.StringConversionFailed:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTableEncryptionError.Write()", value));
        }
    }
}




class FfiConverterOptionalInt64: FfiConverterRustBuffer<long?> {
    public static FfiConverterOptionalInt64 INSTANCE = new FfiConverterOptionalInt64();

    public override long? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterInt64.INSTANCE.Read(stream);
    }

    public override int AllocationSize(long? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterInt64.INSTANCE.AllocationSize((long)value);
        }
    }

    public override void Write(long? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterInt64.INSTANCE.Write((long)value, stream);
        }
    }
}




class FfiConverterOptionalByteArray: FfiConverterRustBuffer<byte[]?> {
    public static FfiConverterOptionalByteArray INSTANCE = new FfiConverterOptionalByteArray();

    public override byte[]? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterByteArray.INSTANCE.Read(stream);
    }

    public override int AllocationSize(byte[]? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterByteArray.INSTANCE.AllocationSize((byte[])value);
        }
    }

    public override void Write(byte[]? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterByteArray.INSTANCE.Write((byte[])value, stream);
        }
    }
}
#pragma warning restore 8625
public static class BacyMethods {
    /// <exception cref="HashException"></exception>
    public static void CrcCompare(string @path, uint @expectedCrc) {

    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_crc_compare(FfiConverterString.INSTANCE.Lower(@path), FfiConverterUInt32.INSTANCE.Lower(@expectedCrc), ref _status)
);
    }


    public static uint CrcComputeBytes(byte[] @buffer) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_crc_compute_bytes(FfiConverterByteArray.INSTANCE.Lower(@buffer), ref _status)
));
    }


    /// <exception cref="HashException"></exception>
    public static uint CrcComputeStreaming(string @path, ulong @bufferSize) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_crc_compute_streaming(FfiConverterString.INSTANCE.Lower(@path), FfiConverterUInt64.INSTANCE.Lower(@bufferSize), ref _status)
));
    }


    public static CrcResult CrcEvaluate(byte[] @data) {
        return FfiConverterTypeCrcResult.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_crc_evaluate(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    /// <exception cref="HashException"></exception>
    public static void CrcForge(string @filePath, uint @targetCrc) {

    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_crc_forge(FfiConverterString.INSTANCE.Lower(@filePath), FfiConverterUInt32.INSTANCE.Lower(@targetCrc), ref _status)
);
    }


    /// <exception cref="HashException"></exception>
    public static void CrcMatchFile(string @filePath, string @targetFilePath) {

    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_crc_match_file(FfiConverterString.INSTANCE.Lower(@filePath), FfiConverterString.INSTANCE.Lower(@targetFilePath), ref _status)
);
    }


    public static string GetFilePath(string @path, long? @crc, bool @noHash, bool @toLower) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_get_file_path(FfiConverterString.INSTANCE.Lower(@path), FfiConverterOptionalInt64.INSTANCE.Lower(@crc), FfiConverterBoolean.INSTANCE.Lower(@noHash), FfiConverterBoolean.INSTANCE.Lower(@toLower), ref _status)
));
    }


    public static uint Md5ComputeDigest(string @source) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_digest(FfiConverterString.INSTANCE.Lower(@source), ref _status)
));
    }


    public static ulong Md5ComputeDigest64(string @source) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_digest64(FfiConverterString.INSTANCE.Lower(@source), ref _status)
));
    }


    public static ulong Md5ComputeDigest64Hmac(string @source, string @key) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_digest64_hmac(FfiConverterString.INSTANCE.Lower(@source), FfiConverterString.INSTANCE.Lower(@key), ref _status)
));
    }


    public static uint Md5ComputeDigestHmac(string @source, string @key) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_digest_hmac(FfiConverterString.INSTANCE.Lower(@source), FfiConverterString.INSTANCE.Lower(@key), ref _status)
));
    }


    public static byte[] Md5ComputeHash(byte[] @source) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_hash(FfiConverterByteArray.INSTANCE.Lower(@source), ref _status)
));
    }


    public static byte[] Md5ComputeHashHmac(byte[] @source, byte[] @key) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_hash_hmac(FfiConverterByteArray.INSTANCE.Lower(@source), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static string Md5ComputeHashStr(string @source) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_hash_str(FfiConverterString.INSTANCE.Lower(@source), ref _status)
));
    }


    public static string Md5ComputeHashStrHmac(string @source, string @key) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_hash_str_hmac(FfiConverterString.INSTANCE.Lower(@source), FfiConverterString.INSTANCE.Lower(@key), ref _status)
));
    }


    public static string Md5ComputeHead(string @source) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_compute_head(FfiConverterString.INSTANCE.Lower(@source), ref _status)
));
    }


    public static string Md5ToHexString(byte[] @data) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_md5_to_hex_string(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    public static byte[] TableCreateKey(string @name) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_create_key(FfiConverterString.INSTANCE.Lower(@name), ref _status)
));
    }


    public static string TableCreatePassword(string @key, ulong @length) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_create_password(FfiConverterString.INSTANCE.Lower(@key), FfiConverterUInt64.INSTANCE.Lower(@length), ref _status)
));
    }


    public static float TableDecryptF32(float @value, byte[] @key) {
        return FfiConverterFloat.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_decrypt_f32(FfiConverterFloat.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static double TableDecryptF64(double @value, byte[] @key) {
        return FfiConverterDouble.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_decrypt_f64(FfiConverterDouble.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static int TableDecryptI32(int @value, byte[] @key) {
        return FfiConverterInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_decrypt_i32(FfiConverterInt32.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static long TableDecryptI64(long @value, byte[] @key) {
        return FfiConverterInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_decrypt_i64(FfiConverterInt64.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    /// <exception cref="TableEncryptionException"></exception>
    public static string TableDecryptString(string @value, byte[] @key) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeTableEncryptionError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_decrypt_string(FfiConverterString.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static uint TableDecryptU32(uint @value, byte[] @key) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_decrypt_u32(FfiConverterUInt32.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static ulong TableDecryptU64(ulong @value, byte[] @key) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_decrypt_u64(FfiConverterUInt64.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static float TableEncryptF32(float @value, byte[] @key) {
        return FfiConverterFloat.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_encrypt_f32(FfiConverterFloat.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static double TableEncryptF64(double @value, byte[] @key) {
        return FfiConverterDouble.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_encrypt_f64(FfiConverterDouble.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static string TableEncryptString(string @value, byte[] @key) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_encrypt_string(FfiConverterString.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static byte[] TableXor(string @name, byte[] @data) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_xor(FfiConverterString.INSTANCE.Lower(@name), FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    public static byte[] XorEncrypt(byte[] @data, ulong @offset, ulong @length) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_encrypt(FfiConverterByteArray.INSTANCE.Lower(@data), FfiConverterUInt64.INSTANCE.Lower(@offset), FfiConverterUInt64.INSTANCE.Lower(@length), ref _status)
));
    }


    public static byte[]? XorEncryptWithKey(byte[] @data, byte[] @key) {
        return FfiConverterOptionalByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_encrypt_with_key(FfiConverterByteArray.INSTANCE.Lower(@data), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static byte[] XorExact(byte[] @value, byte[] @key) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_exact(FfiConverterByteArray.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static byte[] XorInplaceBytes(byte[] @data, byte[] @key) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_inplace_bytes(FfiConverterByteArray.INSTANCE.Lower(@data), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static uint XxhashCalculateHash(byte[] @data) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xxhash_calculate_hash(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    public static ulong XxhashCalculateHash64(byte[] @data) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xxhash_calculate_hash64(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    public static ulong XxhashCalculateHash64Str(string @s) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xxhash_calculate_hash64_str(FfiConverterString.INSTANCE.Lower(@s), ref _status)
));
    }


    public static uint XxhashCalculateHashStr(string @s) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xxhash_calculate_hash_str(FfiConverterString.INSTANCE.Lower(@s), ref _status)
));
    }


    public static bool XxhashGetUseBigEndian() {
        return FfiConverterBoolean.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xxhash_get_use_big_endian( ref _status)
));
    }


    public static void XxhashSetUseBigEndian(bool @value) {

    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xxhash_set_use_big_endian(FfiConverterBoolean.INSTANCE.Lower(@value), ref _status)
);
    }


}
