// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.10.0+v0.29.4
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
namespace BACY;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_bacy_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_bacy_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
internal class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

internal class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

internal class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

internal class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

internal class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

internal class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

internal class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

internal class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: UniffiException
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: UniffiException
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0 && !objType.IsArray) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
             //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
             //for all values as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
             //This extra code tests to not call "Dispose" for a List<int>()
             //for all keys as "int" and alike doesn't support interface "IDisposable"
             var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
             var elementValuesTypeCode = Type.GetTypeCode(elementType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action){
        foreach (var item in items) {
            action(item);
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer) {
#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();
    public short ReadShort() => (short)ReadUShort();
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
static class _UniFFILib {
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFuture
    {
        public ulong @handle;
        public IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructPointer
    {
        public IntPtr @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompletePointer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructPointer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructVoid @result
    );
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        }

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint uniffi_bacy_fn_func_calculate_crc32(RustBuffer @path,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_calculate_md5(RustBuffer @path,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong uniffi_bacy_fn_func_calculate_xxhash(RustBuffer @data,sbyte @bit64,sbyte @endian,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern double uniffi_bacy_fn_func_convert_double(double @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern float uniffi_bacy_fn_func_convert_float(float @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern int uniffi_bacy_fn_func_convert_int(int @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern long uniffi_bacy_fn_func_convert_long(long @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_convert_string(RustBuffer @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint uniffi_bacy_fn_func_convert_uint(uint @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong uniffi_bacy_fn_func_convert_ulong(ulong @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_create_key(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_deserialize_media_catalog(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_deserialize_table_catalog(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern double uniffi_bacy_fn_func_encrypt_double(double @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern float uniffi_bacy_fn_func_encrypt_float(float @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_encrypt_name(RustBuffer @filename,long @crc,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_encrypt_string(RustBuffer @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_evaluate_crc32(RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_extract_all_zip_files(RustBuffer @zipData,RustBuffer @filename,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_extract_zip_file(RustBuffer @zipData,RustBuffer @filename,RustBuffer @fileToExtract,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_bacy_fn_func_forge_crc(RustBuffer @filePath,uint @targetCrc,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_bacy_fn_func_match_crc(RustBuffer @filePath,RustBuffer @targetFilePath,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_media_catalog_to_json(RustBuffer @catalog,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_bacy_fn_func_set_use_encryption(sbyte @enabled,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_table_catalog_to_json(RustBuffer @catalog,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte uniffi_bacy_fn_func_use_encryption(ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_xor_bytes(RustBuffer @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_xor_data(RustBuffer @name,RustBuffer @data,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern int uniffi_bacy_fn_func_xor_int32(int @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern long uniffi_bacy_fn_func_xor_int64(long @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_bacy_fn_func_xor_str(RustBuffer @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint uniffi_bacy_fn_func_xor_uint32(uint @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong uniffi_bacy_fn_func_xor_uint64(ulong @value,RustBuffer @key,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_bacy_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_bacy_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_bacy_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_u8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_u8(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_u8(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte ffi_bacy_rust_future_complete_u8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_i8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_i8(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_i8(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte ffi_bacy_rust_future_complete_i8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_u16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_u16(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_u16(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort ffi_bacy_rust_future_complete_u16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_i16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_i16(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_i16(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern short ffi_bacy_rust_future_complete_i16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_u32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_u32(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_u32(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_bacy_rust_future_complete_u32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_i32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_i32(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_i32(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern int ffi_bacy_rust_future_complete_i32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_u64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_u64(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_u64(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong ffi_bacy_rust_future_complete_u64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_i64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_i64(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_i64(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern long ffi_bacy_rust_future_complete_i64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_f32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_f32(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_f32(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern float ffi_bacy_rust_future_complete_f32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_f64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_f64(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_f64(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern double ffi_bacy_rust_future_complete_f64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_pointer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_pointer(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_pointer(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ffi_bacy_rust_future_complete_pointer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_rust_buffer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_rust_buffer(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_rust_buffer(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_bacy_rust_future_complete_rust_buffer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_poll_void(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_cancel_void(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_free_void(IntPtr @handle
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_bacy_rust_future_complete_void(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_calculate_crc32(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_calculate_md5(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_calculate_xxhash(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_convert_double(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_convert_float(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_convert_int(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_convert_long(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_convert_string(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_convert_uint(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_convert_ulong(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_create_key(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_deserialize_media_catalog(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_deserialize_table_catalog(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_encrypt_double(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_encrypt_float(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_encrypt_name(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_encrypt_string(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_evaluate_crc32(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_extract_all_zip_files(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_extract_zip_file(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_forge_crc(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_match_crc(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_media_catalog_to_json(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_set_use_encryption(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_table_catalog_to_json(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_use_encryption(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_xor_bytes(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_xor_data(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_xor_int32(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_xor_int64(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_xor_str(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_xor_uint32(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_bacy_checksum_func_xor_uint64(
    );

    [DllImport("bacy", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_bacy_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_bacy_uniffi_contract_version();
        if (29 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"BACY: uniffi bindings expected version `29`, library returned `{scaffolding_contract_version}`");
        }
    }

    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_calculate_crc32();
            if (checksum != 30698) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_calculate_crc32` checksum `30698`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_calculate_md5();
            if (checksum != 48336) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_calculate_md5` checksum `48336`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_calculate_xxhash();
            if (checksum != 38510) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_calculate_xxhash` checksum `38510`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_convert_double();
            if (checksum != 2029) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_convert_double` checksum `2029`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_convert_float();
            if (checksum != 9403) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_convert_float` checksum `9403`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_convert_int();
            if (checksum != 5671) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_convert_int` checksum `5671`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_convert_long();
            if (checksum != 25517) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_convert_long` checksum `25517`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_convert_string();
            if (checksum != 59227) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_convert_string` checksum `59227`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_convert_uint();
            if (checksum != 15412) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_convert_uint` checksum `15412`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_convert_ulong();
            if (checksum != 5197) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_convert_ulong` checksum `5197`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_create_key();
            if (checksum != 51014) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_create_key` checksum `51014`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_deserialize_media_catalog();
            if (checksum != 50020) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_deserialize_media_catalog` checksum `50020`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_deserialize_table_catalog();
            if (checksum != 1479) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_deserialize_table_catalog` checksum `1479`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_encrypt_double();
            if (checksum != 65458) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_encrypt_double` checksum `65458`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_encrypt_float();
            if (checksum != 31857) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_encrypt_float` checksum `31857`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_encrypt_name();
            if (checksum != 18305) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_encrypt_name` checksum `18305`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_encrypt_string();
            if (checksum != 1359) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_encrypt_string` checksum `1359`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_evaluate_crc32();
            if (checksum != 8610) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_evaluate_crc32` checksum `8610`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_extract_all_zip_files();
            if (checksum != 40532) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_extract_all_zip_files` checksum `40532`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_extract_zip_file();
            if (checksum != 45457) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_extract_zip_file` checksum `45457`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_forge_crc();
            if (checksum != 49205) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_forge_crc` checksum `49205`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_match_crc();
            if (checksum != 40070) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_match_crc` checksum `40070`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_media_catalog_to_json();
            if (checksum != 57872) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_media_catalog_to_json` checksum `57872`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_set_use_encryption();
            if (checksum != 1339) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_set_use_encryption` checksum `1339`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_table_catalog_to_json();
            if (checksum != 8791) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_table_catalog_to_json` checksum `8791`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_use_encryption();
            if (checksum != 31500) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_use_encryption` checksum `31500`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_bytes();
            if (checksum != 22827) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_bytes` checksum `22827`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_data();
            if (checksum != 15286) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_data` checksum `15286`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_int32();
            if (checksum != 48191) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_int32` checksum `48191`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_int64();
            if (checksum != 11821) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_int64` checksum `11821`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_str();
            if (checksum != 23130) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_str` checksum `23130`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_uint32();
            if (checksum != 46484) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_uint32` checksum `46484`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_bacy_checksum_func_xor_uint64();
            if (checksum != 39429) {
                throw new UniffiContractChecksumException($"BACY: uniffi bindings expected function `uniffi_bacy_checksum_func_xor_uint64` checksum `39429`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterUInt32: FfiConverter<uint, uint> {
    public static FfiConverterUInt32 INSTANCE = new FfiConverterUInt32();

    public override uint Lift(uint value) {
        return value;
    }

    public override uint Read(BigEndianStream stream) {
        return stream.ReadUInt();
    }

    public override uint Lower(uint value) {
        return value;
    }

    public override int AllocationSize(uint value) {
        return 4;
    }

    public override void Write(uint value, BigEndianStream stream) {
        stream.WriteUInt(value);
    }
}



class FfiConverterInt32: FfiConverter<int, int> {
    public static FfiConverterInt32 INSTANCE = new FfiConverterInt32();

    public override int Lift(int value) {
        return value;
    }

    public override int Read(BigEndianStream stream) {
        return stream.ReadInt();
    }

    public override int Lower(int value) {
        return value;
    }

    public override int AllocationSize(int value) {
        return 4;
    }

    public override void Write(int value, BigEndianStream stream) {
        stream.WriteInt(value);
    }
}



class FfiConverterUInt64: FfiConverter<ulong, ulong> {
    public static FfiConverterUInt64 INSTANCE = new FfiConverterUInt64();

    public override ulong Lift(ulong value) {
        return value;
    }

    public override ulong Read(BigEndianStream stream) {
        return stream.ReadULong();
    }

    public override ulong Lower(ulong value) {
        return value;
    }

    public override int AllocationSize(ulong value) {
        return 8;
    }

    public override void Write(ulong value, BigEndianStream stream) {
        stream.WriteULong(value);
    }
}



class FfiConverterInt64: FfiConverter<long, long> {
    public static FfiConverterInt64 INSTANCE = new FfiConverterInt64();

    public override long Lift(long value) {
        return value;
    }

    public override long Read(BigEndianStream stream) {
        return stream.ReadLong();
    }

    public override long Lower(long value) {
        return value;
    }

    public override int AllocationSize(long value) {
        return 8;
    }

    public override void Write(long value, BigEndianStream stream) {
        stream.WriteLong(value);
    }
}



class FfiConverterFloat: FfiConverter<float, float> {
    public static FfiConverterFloat INSTANCE = new FfiConverterFloat();

    public override float Lift(float value) {
        return value;
    }

    public override float Read(BigEndianStream stream) {
        return stream.ReadFloat();
    }

    public override float Lower(float value) {
        return value;
    }

    public override int AllocationSize(float value) {
        return 4;
    }

    public override void Write(float value, BigEndianStream stream) {
        stream.WriteFloat(value);
    }
}



class FfiConverterDouble: FfiConverter<double, double> {
    public static FfiConverterDouble INSTANCE = new FfiConverterDouble();

    public override double Lift(double value) {
        return value;
    }

    public override double Read(BigEndianStream stream) {
        return stream.ReadDouble();
    }

    public override double Lower(double value) {
        return value;
    }

    public override int AllocationSize(double value) {
        return 8;
    }

    public override void Write(double value, BigEndianStream stream) {
        stream.WriteDouble(value);
    }
}



class FfiConverterBoolean: FfiConverter<bool, sbyte> {
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value) {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream) {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value) {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value) {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream) {
        stream.WriteSByte(Lower(value));
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}




class FfiConverterByteArray: FfiConverterRustBuffer<byte[]> {
    public static FfiConverterByteArray INSTANCE = new FfiConverterByteArray();

    public override byte[] Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        return stream.ReadBytes(length);
    }

    public override int AllocationSize(byte[] value) {
        return 4 + value.Length;
    }

    public override void Write(byte[] value, BigEndianStream stream) {
        stream.WriteInt(value.Length);
        stream.WriteBytes(value);
    }
}



internal record CrcResult (
    uint @value, 
    string @hex
) {
}

class FfiConverterTypeCrcResult: FfiConverterRustBuffer<CrcResult> {
    public static FfiConverterTypeCrcResult INSTANCE = new FfiConverterTypeCrcResult();

    public override CrcResult Read(BigEndianStream stream) {
        return new CrcResult(
            @value: FfiConverterUInt32.INSTANCE.Read(stream),
            @hex: FfiConverterString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(CrcResult value) {
        return 0
            + FfiConverterUInt32.INSTANCE.AllocationSize(value.@value)
            + FfiConverterString.INSTANCE.AllocationSize(value.@hex);
    }

    public override void Write(CrcResult value, BigEndianStream stream) {
            FfiConverterUInt32.INSTANCE.Write(value.@value, stream);
            FfiConverterString.INSTANCE.Write(value.@hex, stream);
    }
}



internal record Media (
    string @path, 
    string @fileName, 
    long @bytes, 
    long @crc, 
    bool @isPrologue, 
    bool @isSplitDownload, 
    int @mediaType
) {
}

class FfiConverterTypeMedia: FfiConverterRustBuffer<Media> {
    public static FfiConverterTypeMedia INSTANCE = new FfiConverterTypeMedia();

    public override Media Read(BigEndianStream stream) {
        return new Media(
            @path: FfiConverterString.INSTANCE.Read(stream),
            @fileName: FfiConverterString.INSTANCE.Read(stream),
            @bytes: FfiConverterInt64.INSTANCE.Read(stream),
            @crc: FfiConverterInt64.INSTANCE.Read(stream),
            @isPrologue: FfiConverterBoolean.INSTANCE.Read(stream),
            @isSplitDownload: FfiConverterBoolean.INSTANCE.Read(stream),
            @mediaType: FfiConverterInt32.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(Media value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@path)
            + FfiConverterString.INSTANCE.AllocationSize(value.@fileName)
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@bytes)
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@crc)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@isPrologue)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@isSplitDownload)
            + FfiConverterInt32.INSTANCE.AllocationSize(value.@mediaType);
    }

    public override void Write(Media value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@path, stream);
            FfiConverterString.INSTANCE.Write(value.@fileName, stream);
            FfiConverterInt64.INSTANCE.Write(value.@bytes, stream);
            FfiConverterInt64.INSTANCE.Write(value.@crc, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@isPrologue, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@isSplitDownload, stream);
            FfiConverterInt32.INSTANCE.Write(value.@mediaType, stream);
    }
}



internal record MediaCatalog (
    Dictionary<string, Media> @table
) {
}

class FfiConverterTypeMediaCatalog: FfiConverterRustBuffer<MediaCatalog> {
    public static FfiConverterTypeMediaCatalog INSTANCE = new FfiConverterTypeMediaCatalog();

    public override MediaCatalog Read(BigEndianStream stream) {
        return new MediaCatalog(
            @table: FfiConverterDictionaryStringTypeMedia.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(MediaCatalog value) {
        return 0
            + FfiConverterDictionaryStringTypeMedia.INSTANCE.AllocationSize(value.@table);
    }

    public override void Write(MediaCatalog value, BigEndianStream stream) {
            FfiConverterDictionaryStringTypeMedia.INSTANCE.Write(value.@table, stream);
    }
}



internal record Table (
    string @name, 
    long @size, 
    long @crc, 
    bool @isInBuild, 
    bool @isChanged, 
    bool @isPrologue, 
    bool @isSplitDownload, 
    string[] @includes
) {
}

class FfiConverterTypeTable: FfiConverterRustBuffer<Table> {
    public static FfiConverterTypeTable INSTANCE = new FfiConverterTypeTable();

    public override Table Read(BigEndianStream stream) {
        return new Table(
            @name: FfiConverterString.INSTANCE.Read(stream),
            @size: FfiConverterInt64.INSTANCE.Read(stream),
            @crc: FfiConverterInt64.INSTANCE.Read(stream),
            @isInBuild: FfiConverterBoolean.INSTANCE.Read(stream),
            @isChanged: FfiConverterBoolean.INSTANCE.Read(stream),
            @isPrologue: FfiConverterBoolean.INSTANCE.Read(stream),
            @isSplitDownload: FfiConverterBoolean.INSTANCE.Read(stream),
            @includes: FfiConverterSequenceString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(Table value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@name)
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@size)
            + FfiConverterInt64.INSTANCE.AllocationSize(value.@crc)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@isInBuild)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@isChanged)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@isPrologue)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@isSplitDownload)
            + FfiConverterSequenceString.INSTANCE.AllocationSize(value.@includes);
    }

    public override void Write(Table value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@name, stream);
            FfiConverterInt64.INSTANCE.Write(value.@size, stream);
            FfiConverterInt64.INSTANCE.Write(value.@crc, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@isInBuild, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@isChanged, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@isPrologue, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@isSplitDownload, stream);
            FfiConverterSequenceString.INSTANCE.Write(value.@includes, stream);
    }
}



internal record TableCatalog (
    Dictionary<string, Table> @table
) {
}

class FfiConverterTypeTableCatalog: FfiConverterRustBuffer<TableCatalog> {
    public static FfiConverterTypeTableCatalog INSTANCE = new FfiConverterTypeTableCatalog();

    public override TableCatalog Read(BigEndianStream stream) {
        return new TableCatalog(
            @table: FfiConverterDictionaryStringTypeTable.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(TableCatalog value) {
        return 0
            + FfiConverterDictionaryStringTypeTable.INSTANCE.AllocationSize(value.@table);
    }

    public override void Write(TableCatalog value, BigEndianStream stream) {
            FfiConverterDictionaryStringTypeTable.INSTANCE.Write(value.@table, stream);
    }
}



internal record ZipFileEntry (
    string @name, 
    byte[] @data
) {
}

class FfiConverterTypeZipFileEntry: FfiConverterRustBuffer<ZipFileEntry> {
    public static FfiConverterTypeZipFileEntry INSTANCE = new FfiConverterTypeZipFileEntry();

    public override ZipFileEntry Read(BigEndianStream stream) {
        return new ZipFileEntry(
            @name: FfiConverterString.INSTANCE.Read(stream),
            @data: FfiConverterByteArray.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(ZipFileEntry value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@name)
            + FfiConverterByteArray.INSTANCE.AllocationSize(value.@data);
    }

    public override void Write(ZipFileEntry value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@name, stream);
            FfiConverterByteArray.INSTANCE.Write(value.@data, stream);
    }
}





internal class CatalogException: UniffiException {
    CatalogException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.
    
    public class MemoryPack: CatalogException {
        public MemoryPack(string message): base(message) {}
    }
    
    public class Json: CatalogException {
        public Json(string message): base(message) {}
    }
    
    public class SerializationFailed: CatalogException {
        public SerializationFailed(string message): base(message) {}
    }
    
    public class DeserializationFailed: CatalogException {
        public DeserializationFailed(string message): base(message) {}
    }
    
}

class FfiConverterTypeCatalogError : FfiConverterRustBuffer<CatalogException>, CallStatusErrorHandler<CatalogException> {
    public static FfiConverterTypeCatalogError INSTANCE = new FfiConverterTypeCatalogError();

    public override CatalogException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new CatalogException.MemoryPack(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new CatalogException.Json(FfiConverterString.INSTANCE.Read(stream));
            case 3: return new CatalogException.SerializationFailed(FfiConverterString.INSTANCE.Read(stream));
            case 4: return new CatalogException.DeserializationFailed(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeCatalogError.Read()", value));
        }
    }

    public override int AllocationSize(CatalogException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(CatalogException value, BigEndianStream stream) {
        switch (value) {
            case CatalogException.MemoryPack:
                stream.WriteInt(1);
                break;
            case CatalogException.Json:
                stream.WriteInt(2);
                break;
            case CatalogException.SerializationFailed:
                stream.WriteInt(3);
                break;
            case CatalogException.DeserializationFailed:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeCatalogError.Write()", value));
        }
    }
}





internal class HashException: UniffiException {
    HashException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.
    
    public class Io: HashException {
        public Io(string message): base(message) {}
    }
    
    public class InvalidPath: HashException {
        public InvalidPath(string message): base(message) {}
    }
    
    public class Mismatch: HashException {
        public Mismatch(string message): base(message) {}
    }
    
}

class FfiConverterTypeHashError : FfiConverterRustBuffer<HashException>, CallStatusErrorHandler<HashException> {
    public static FfiConverterTypeHashError INSTANCE = new FfiConverterTypeHashError();

    public override HashException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new HashException.Io(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new HashException.InvalidPath(FfiConverterString.INSTANCE.Read(stream));
            case 3: return new HashException.Mismatch(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeHashError.Read()", value));
        }
    }

    public override int AllocationSize(HashException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(HashException value, BigEndianStream stream) {
        switch (value) {
            case HashException.Io:
                stream.WriteInt(1);
                break;
            case HashException.InvalidPath:
                stream.WriteInt(2);
                break;
            case HashException.Mismatch:
                stream.WriteInt(3);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeHashError.Write()", value));
        }
    }
}





internal class TableEncryptionException: UniffiException {
    TableEncryptionException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.
    
    public class Base64Decode: TableEncryptionException {
        public Base64Decode(string message): base(message) {}
    }
    
    public class StringConversionFailed: TableEncryptionException {
        public StringConversionFailed(string message): base(message) {}
    }
    
}

class FfiConverterTypeTableEncryptionError : FfiConverterRustBuffer<TableEncryptionException>, CallStatusErrorHandler<TableEncryptionException> {
    public static FfiConverterTypeTableEncryptionError INSTANCE = new FfiConverterTypeTableEncryptionError();

    public override TableEncryptionException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new TableEncryptionException.Base64Decode(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new TableEncryptionException.StringConversionFailed(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTableEncryptionError.Read()", value));
        }
    }

    public override int AllocationSize(TableEncryptionException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(TableEncryptionException value, BigEndianStream stream) {
        switch (value) {
            case TableEncryptionException.Base64Decode:
                stream.WriteInt(1);
                break;
            case TableEncryptionException.StringConversionFailed:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTableEncryptionError.Write()", value));
        }
    }
}





internal class TableZipException: UniffiException {
    TableZipException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.
    
    public class Io: TableZipException {
        public Io(string message): base(message) {}
    }
    
    public class Zip: TableZipException {
        public Zip(string message): base(message) {}
    }
    
    public class Base64Decode: TableZipException {
        public Base64Decode(string message): base(message) {}
    }
    
    public class EncodeSlice: TableZipException {
        public EncodeSlice(string message): base(message) {}
    }
    
}

class FfiConverterTypeTableZipError : FfiConverterRustBuffer<TableZipException>, CallStatusErrorHandler<TableZipException> {
    public static FfiConverterTypeTableZipError INSTANCE = new FfiConverterTypeTableZipError();

    public override TableZipException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new TableZipException.Io(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new TableZipException.Zip(FfiConverterString.INSTANCE.Read(stream));
            case 3: return new TableZipException.Base64Decode(FfiConverterString.INSTANCE.Read(stream));
            case 4: return new TableZipException.EncodeSlice(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTableZipError.Read()", value));
        }
    }

    public override int AllocationSize(TableZipException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(TableZipException value, BigEndianStream stream) {
        switch (value) {
            case TableZipException.Io:
                stream.WriteInt(1);
                break;
            case TableZipException.Zip:
                stream.WriteInt(2);
                break;
            case TableZipException.Base64Decode:
                stream.WriteInt(3);
                break;
            case TableZipException.EncodeSlice:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTableZipError.Write()", value));
        }
    }
}




class FfiConverterSequenceString: FfiConverterRustBuffer<string[]> {
    public static FfiConverterSequenceString INSTANCE = new FfiConverterSequenceString();

    public override string[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new string[(length)];
        var readFn = FfiConverterString.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(string[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(string[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterString.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}




class FfiConverterSequenceTypeZipFileEntry: FfiConverterRustBuffer<ZipFileEntry[]> {
    public static FfiConverterSequenceTypeZipFileEntry INSTANCE = new FfiConverterSequenceTypeZipFileEntry();

    public override ZipFileEntry[]  Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        if (length == 0) {
            return [];
        }

        var result = new ZipFileEntry[(length)];
        var readFn = FfiConverterTypeZipFileEntry.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result[i] = readFn(stream);
        }
        return result;
    }

    public override int AllocationSize(ZipFileEntry[]  value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeZipFileEntry.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(ZipFileEntry[] value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Length);
        var writerFn = FfiConverterTypeZipFileEntry.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}




class FfiConverterDictionaryStringTypeMedia: FfiConverterRustBuffer<Dictionary<string, Media>> {
    public static FfiConverterDictionaryStringTypeMedia INSTANCE = new FfiConverterDictionaryStringTypeMedia();

    public override Dictionary<string, Media> Read(BigEndianStream stream) {
        var len = stream.ReadInt();
        var result = new Dictionary<string, Media>(len);
        var readerKey = FfiConverterString.INSTANCE.Read;
        var readerValue = FfiConverterTypeMedia.INSTANCE.Read;
        for (int i = 0; i < len; i++) {
            var key = readerKey(stream);
            var value = readerValue(stream);
            result[key] = value;
        }

        return result;
    }

    public override int AllocationSize(Dictionary<string, Media> value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationKeySizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var allocationKValueSizeFn = FfiConverterTypeMedia.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationKeySizeFn(item.Key) + allocationKValueSizeFn(item.Value));
        return sizeForLength + sizeForItems;
    }

    public override void Write(Dictionary<string, Media> value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Count);
        var writerKey = FfiConverterString.INSTANCE.Write;
        var writerValue = FfiConverterTypeMedia.INSTANCE.Write;
        foreach (var item in value) {
            writerKey(item.Key, stream);
            writerValue(item.Value, stream);
        }
    }
}




class FfiConverterDictionaryStringTypeTable: FfiConverterRustBuffer<Dictionary<string, Table>> {
    public static FfiConverterDictionaryStringTypeTable INSTANCE = new FfiConverterDictionaryStringTypeTable();

    public override Dictionary<string, Table> Read(BigEndianStream stream) {
        var len = stream.ReadInt();
        var result = new Dictionary<string, Table>(len);
        var readerKey = FfiConverterString.INSTANCE.Read;
        var readerValue = FfiConverterTypeTable.INSTANCE.Read;
        for (int i = 0; i < len; i++) {
            var key = readerKey(stream);
            var value = readerValue(stream);
            result[key] = value;
        }

        return result;
    }

    public override int AllocationSize(Dictionary<string, Table> value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationKeySizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var allocationKValueSizeFn = FfiConverterTypeTable.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationKeySizeFn(item.Key) + allocationKValueSizeFn(item.Value));
        return sizeForLength + sizeForItems;
    }

    public override void Write(Dictionary<string, Table> value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Count);
        var writerKey = FfiConverterString.INSTANCE.Write;
        var writerValue = FfiConverterTypeTable.INSTANCE.Write;
        foreach (var item in value) {
            writerKey(item.Key, stream);
            writerValue(item.Value, stream);
        }
    }
}
#pragma warning restore 8625
internal static class BacyMethods {
    /// <exception cref="HashException"></exception>
    public static uint CalculateCrc32(string @path) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_calculate_crc32(FfiConverterString.INSTANCE.Lower(@path), ref _status)
));
    }


    /// <exception cref="HashException"></exception>
    public static string CalculateMd5(string @path) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_calculate_md5(FfiConverterString.INSTANCE.Lower(@path), ref _status)
));
    }


    public static ulong CalculateXxhash(byte[] @data, bool @bit64, bool @endian) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_calculate_xxhash(FfiConverterByteArray.INSTANCE.Lower(@data), FfiConverterBoolean.INSTANCE.Lower(@bit64), FfiConverterBoolean.INSTANCE.Lower(@endian), ref _status)
));
    }


    public static double ConvertDouble(double @value, byte[] @key) {
        return FfiConverterDouble.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_convert_double(FfiConverterDouble.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static float ConvertFloat(float @value, byte[] @key) {
        return FfiConverterFloat.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_convert_float(FfiConverterFloat.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static int ConvertInt(int @value, byte[] @key) {
        return FfiConverterInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_convert_int(FfiConverterInt32.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static long ConvertLong(long @value, byte[] @key) {
        return FfiConverterInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_convert_long(FfiConverterInt64.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    /// <exception cref="TableEncryptionException"></exception>
    public static string ConvertString(string @value, byte[] @key) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeTableEncryptionError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_convert_string(FfiConverterString.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static uint ConvertUint(uint @value, byte[] @key) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_convert_uint(FfiConverterUInt32.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static ulong ConvertUlong(ulong @value, byte[] @key) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_convert_ulong(FfiConverterUInt64.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static byte[] CreateKey(byte[] @data) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_create_key(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    /// <exception cref="CatalogException"></exception>
    public static MediaCatalog DeserializeMediaCatalog(byte[] @data) {
        return FfiConverterTypeMediaCatalog.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeCatalogError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_deserialize_media_catalog(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    /// <exception cref="CatalogException"></exception>
    public static TableCatalog DeserializeTableCatalog(byte[] @data) {
        return FfiConverterTypeTableCatalog.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeCatalogError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_deserialize_table_catalog(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    public static double EncryptDouble(double @value, byte[] @key) {
        return FfiConverterDouble.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_encrypt_double(FfiConverterDouble.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static float EncryptFloat(float @value, byte[] @key) {
        return FfiConverterFloat.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_encrypt_float(FfiConverterFloat.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    /// <exception cref="HashException"></exception>
    public static string EncryptName(string @filename, long @crc) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_encrypt_name(FfiConverterString.INSTANCE.Lower(@filename), FfiConverterInt64.INSTANCE.Lower(@crc), ref _status)
));
    }


    /// <exception cref="TableEncryptionException"></exception>
    public static string EncryptString(string @value, byte[] @key) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeTableEncryptionError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_encrypt_string(FfiConverterString.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static CrcResult EvaluateCrc32(byte[] @data) {
        return FfiConverterTypeCrcResult.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_evaluate_crc32(FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    /// <exception cref="TableZipException"></exception>
    public static ZipFileEntry[] ExtractAllZipFiles(byte[] @zipData, string @filename) {
        return FfiConverterSequenceTypeZipFileEntry.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeTableZipError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_extract_all_zip_files(FfiConverterByteArray.INSTANCE.Lower(@zipData), FfiConverterString.INSTANCE.Lower(@filename), ref _status)
));
    }


    /// <exception cref="TableZipException"></exception>
    public static byte[] ExtractZipFile(byte[] @zipData, string @filename, string @fileToExtract) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeTableZipError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_extract_zip_file(FfiConverterByteArray.INSTANCE.Lower(@zipData), FfiConverterString.INSTANCE.Lower(@filename), FfiConverterString.INSTANCE.Lower(@fileToExtract), ref _status)
));
    }


    /// <exception cref="HashException"></exception>
    public static void ForgeCrc(string @filePath, uint @targetCrc) {
        
    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_forge_crc(FfiConverterString.INSTANCE.Lower(@filePath), FfiConverterUInt32.INSTANCE.Lower(@targetCrc), ref _status)
);
    }


    /// <exception cref="HashException"></exception>
    public static void MatchCrc(string @filePath, string @targetFilePath) {
        
    _UniffiHelpers.RustCallWithError(FfiConverterTypeHashError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_match_crc(FfiConverterString.INSTANCE.Lower(@filePath), FfiConverterString.INSTANCE.Lower(@targetFilePath), ref _status)
);
    }


    /// <exception cref="CatalogException"></exception>
    public static string MediaCatalogToJson(MediaCatalog @catalog) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeCatalogError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_media_catalog_to_json(FfiConverterTypeMediaCatalog.INSTANCE.Lower(@catalog), ref _status)
));
    }


    public static void SetUseEncryption(bool @enabled) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_set_use_encryption(FfiConverterBoolean.INSTANCE.Lower(@enabled), ref _status)
);
    }


    /// <exception cref="CatalogException"></exception>
    public static string TableCatalogToJson(TableCatalog @catalog) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeCatalogError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_table_catalog_to_json(FfiConverterTypeTableCatalog.INSTANCE.Lower(@catalog), ref _status)
));
    }


    public static bool UseEncryption() {
        return FfiConverterBoolean.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_use_encryption( ref _status)
));
    }


    public static byte[] XorBytes(byte[] @value, byte[] @key) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_bytes(FfiConverterByteArray.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static byte[] XorData(string @name, byte[] @data) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_data(FfiConverterString.INSTANCE.Lower(@name), FfiConverterByteArray.INSTANCE.Lower(@data), ref _status)
));
    }


    public static int XorInt32(int @value, byte[] @key) {
        return FfiConverterInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_int32(FfiConverterInt32.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static long XorInt64(long @value, byte[] @key) {
        return FfiConverterInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_int64(FfiConverterInt64.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static byte[] XorStr(byte[] @value, byte[] @key) {
        return FfiConverterByteArray.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_str(FfiConverterByteArray.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static uint XorUint32(uint @value, byte[] @key) {
        return FfiConverterUInt32.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_uint32(FfiConverterUInt32.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


    public static ulong XorUint64(ulong @value, byte[] @key) {
        return FfiConverterUInt64.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_bacy_fn_func_xor_uint64(FfiConverterUInt64.INSTANCE.Lower(@value), FfiConverterByteArray.INSTANCE.Lower(@key), ref _status)
));
    }


}

