// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.10.0+v0.29.4
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
namespace BABR.BAADCore;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_baad_core_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_baad_core_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

public class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

public class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

public class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

public class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

public class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

public class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

public class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: UniffiException
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: UniffiException
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0 && !objType.IsArray) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
             //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
             //for all values as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
             //This extra code tests to not call "Dispose" for a List<int>()
             //for all keys as "int" and alike doesn't support interface "IDisposable"
             var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
             var elementValuesTypeCode = Type.GetTypeCode(elementType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action){
        foreach (var item in items) {
            action(item);
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer) {
#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();
    public short ReadShort() => (short)ReadUShort();
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
static partial class _UniFFILib {
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFuture
    {
        public ulong @handle;
        public IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructPointer
    {
        public IntPtr @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompletePointer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructPointer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructVoid @result
    );
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        }

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr uniffi_baad_core_fn_func_clear_all(RustBuffer @dir
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr uniffi_baad_core_fn_func_create_parent_dir(RustBuffer @path
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_baad_core_fn_func_data_dir(ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_baad_core_fn_func_get_data_path(RustBuffer @filename,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer uniffi_baad_core_fn_func_get_feature_config(ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr uniffi_baad_core_fn_func_get_output_dir(RustBuffer @path
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_init_logging(RustBuffer @config,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_init_logging_default(ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr uniffi_baad_core_fn_func_is_dir_empty(RustBuffer @path
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr uniffi_baad_core_fn_func_load_file(RustBuffer @path
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_debug(RustBuffer @message,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_debug_with_field(RustBuffer @message,RustBuffer @fieldName,RustBuffer @fieldValue,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_debug_with_fields(RustBuffer @message,RustBuffer @fields,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_error(RustBuffer @message,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_error_from_string(RustBuffer @errorMessage,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_error_with_field(RustBuffer @message,RustBuffer @fieldName,RustBuffer @fieldValue,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_error_with_fields(RustBuffer @message,RustBuffer @fields,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_info(RustBuffer @message,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_info_with_field(RustBuffer @message,RustBuffer @fieldName,RustBuffer @fieldValue,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_info_with_fields(RustBuffer @message,RustBuffer @fields,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_recoverable_error_from_string(RustBuffer @errorMessage,RustBuffer @recoveryAction,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_trace(RustBuffer @message,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_trace_with_field(RustBuffer @message,RustBuffer @fieldName,RustBuffer @fieldValue,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_trace_with_fields(RustBuffer @message,RustBuffer @fields,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_warn(RustBuffer @message,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_warn_with_field(RustBuffer @message,RustBuffer @fieldName,RustBuffer @fieldValue,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_log_warn_with_fields(RustBuffer @message,RustBuffer @fields,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr uniffi_baad_core_fn_func_save_file(RustBuffer @path,RustBuffer @content
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_set_app_name(RustBuffer @name,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void uniffi_baad_core_fn_func_set_data_dir(RustBuffer @path,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_baad_core_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_baad_core_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_baad_core_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_u8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_u8(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_u8(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial byte ffi_baad_core_rust_future_complete_u8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_i8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_i8(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_i8(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial sbyte ffi_baad_core_rust_future_complete_i8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_u16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_u16(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_u16(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort ffi_baad_core_rust_future_complete_u16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_i16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_i16(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_i16(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial short ffi_baad_core_rust_future_complete_i16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_u32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_u32(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_u32(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint ffi_baad_core_rust_future_complete_u32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_i32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_i32(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_i32(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial int ffi_baad_core_rust_future_complete_i32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_u64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_u64(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_u64(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ulong ffi_baad_core_rust_future_complete_u64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_i64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_i64(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_i64(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial long ffi_baad_core_rust_future_complete_i64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_f32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_f32(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_f32(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial float ffi_baad_core_rust_future_complete_f32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_f64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_f64(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_f64(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial double ffi_baad_core_rust_future_complete_f64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_pointer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_pointer(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_pointer(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial IntPtr ffi_baad_core_rust_future_complete_pointer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_rust_buffer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_rust_buffer(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_rust_buffer(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial RustBuffer ffi_baad_core_rust_future_complete_rust_buffer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_poll_void(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_cancel_void(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_free_void(IntPtr @handle
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial void ffi_baad_core_rust_future_complete_void(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_clear_all(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_create_parent_dir(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_data_dir(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_get_data_path(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_get_feature_config(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_get_output_dir(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_init_logging(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_init_logging_default(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_is_dir_empty(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_load_file(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_debug(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_debug_with_field(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_debug_with_fields(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_error(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_error_from_string(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_error_with_field(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_error_with_fields(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_info(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_info_with_field(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_info_with_fields(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_recoverable_error_from_string(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_trace(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_trace_with_field(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_trace_with_fields(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_warn(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_warn_with_field(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_log_warn_with_fields(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_save_file(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_set_app_name(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial ushort uniffi_baad_core_checksum_func_set_data_dir(
    );

    [LibraryImport("baad_core")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial uint ffi_baad_core_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_baad_core_uniffi_contract_version();
        if (29 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"BAADCore: uniffi bindings expected version `29`, library returned `{scaffolding_contract_version}`");
        }
    }

    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_clear_all();
            if (checksum != 3738) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_clear_all` checksum `3738`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_create_parent_dir();
            if (checksum != 52756) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_create_parent_dir` checksum `52756`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_data_dir();
            if (checksum != 19717) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_data_dir` checksum `19717`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_get_data_path();
            if (checksum != 22654) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_get_data_path` checksum `22654`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_get_feature_config();
            if (checksum != 15996) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_get_feature_config` checksum `15996`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_get_output_dir();
            if (checksum != 39411) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_get_output_dir` checksum `39411`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_init_logging();
            if (checksum != 58565) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_init_logging` checksum `58565`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_init_logging_default();
            if (checksum != 42340) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_init_logging_default` checksum `42340`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_is_dir_empty();
            if (checksum != 34433) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_is_dir_empty` checksum `34433`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_load_file();
            if (checksum != 14605) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_load_file` checksum `14605`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_debug();
            if (checksum != 57349) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_debug` checksum `57349`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_debug_with_field();
            if (checksum != 29403) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_debug_with_field` checksum `29403`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_debug_with_fields();
            if (checksum != 45317) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_debug_with_fields` checksum `45317`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_error();
            if (checksum != 6284) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_error` checksum `6284`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_error_from_string();
            if (checksum != 6942) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_error_from_string` checksum `6942`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_error_with_field();
            if (checksum != 45353) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_error_with_field` checksum `45353`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_error_with_fields();
            if (checksum != 64124) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_error_with_fields` checksum `64124`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_info();
            if (checksum != 7152) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_info` checksum `7152`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_info_with_field();
            if (checksum != 8500) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_info_with_field` checksum `8500`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_info_with_fields();
            if (checksum != 2166) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_info_with_fields` checksum `2166`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_recoverable_error_from_string();
            if (checksum != 65090) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_recoverable_error_from_string` checksum `65090`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_trace();
            if (checksum != 25040) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_trace` checksum `25040`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_trace_with_field();
            if (checksum != 49472) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_trace_with_field` checksum `49472`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_trace_with_fields();
            if (checksum != 50270) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_trace_with_fields` checksum `50270`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_warn();
            if (checksum != 27846) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_warn` checksum `27846`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_warn_with_field();
            if (checksum != 39338) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_warn_with_field` checksum `39338`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_log_warn_with_fields();
            if (checksum != 63807) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_log_warn_with_fields` checksum `63807`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_save_file();
            if (checksum != 21264) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_save_file` checksum `21264`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_set_app_name();
            if (checksum != 6953) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_set_app_name` checksum `6953`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_baad_core_checksum_func_set_data_dir();
            if (checksum != 17024) {
                throw new UniffiContractChecksumException($"BAADCore: uniffi bindings expected function `uniffi_baad_core_checksum_func_set_data_dir` checksum `17024`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterBoolean: FfiConverter<bool, sbyte> {
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value) {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream) {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value) {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value) {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream) {
        stream.WriteSByte(Lower(value));
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}




class FfiConverterByteArray: FfiConverterRustBuffer<byte[]> {
    public static FfiConverterByteArray INSTANCE = new FfiConverterByteArray();

    public override byte[] Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        return stream.ReadBytes(length);
    }

    public override int AllocationSize(byte[] value) {
        return 4 + value.Length;
    }

    public override void Write(byte[] value, BigEndianStream stream) {
        stream.WriteInt(value.Length);
        stream.WriteBytes(value);
    }
}



public record FeatureConfig (
    bool @logsEnabled, 
    bool @debugEnabled, 
    bool @errorEnabled
) {
}

class FfiConverterTypeFeatureConfig: FfiConverterRustBuffer<FeatureConfig> {
    public static FfiConverterTypeFeatureConfig INSTANCE = new FfiConverterTypeFeatureConfig();

    public override FeatureConfig Read(BigEndianStream stream) {
        return new FeatureConfig(
            @logsEnabled: FfiConverterBoolean.INSTANCE.Read(stream),
            @debugEnabled: FfiConverterBoolean.INSTANCE.Read(stream),
            @errorEnabled: FfiConverterBoolean.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(FeatureConfig value) {
        return 0
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@logsEnabled)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@debugEnabled)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@errorEnabled);
    }

    public override void Write(FeatureConfig value, BigEndianStream stream) {
            FfiConverterBoolean.INSTANCE.Write(value.@logsEnabled, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@debugEnabled, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@errorEnabled, stream);
    }
}



public record LoggingConfig (
    bool @enableConsole, 
    bool @enableJson, 
    bool @enableDebug, 
    bool @verboseMode, 
    bool @includeTimestamps
) {
}

class FfiConverterTypeLoggingConfig: FfiConverterRustBuffer<LoggingConfig> {
    public static FfiConverterTypeLoggingConfig INSTANCE = new FfiConverterTypeLoggingConfig();

    public override LoggingConfig Read(BigEndianStream stream) {
        return new LoggingConfig(
            @enableConsole: FfiConverterBoolean.INSTANCE.Read(stream),
            @enableJson: FfiConverterBoolean.INSTANCE.Read(stream),
            @enableDebug: FfiConverterBoolean.INSTANCE.Read(stream),
            @verboseMode: FfiConverterBoolean.INSTANCE.Read(stream),
            @includeTimestamps: FfiConverterBoolean.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(LoggingConfig value) {
        return 0
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@enableConsole)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@enableJson)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@enableDebug)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@verboseMode)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@includeTimestamps);
    }

    public override void Write(LoggingConfig value, BigEndianStream stream) {
            FfiConverterBoolean.INSTANCE.Write(value.@enableConsole, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@enableJson, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@enableDebug, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@verboseMode, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@includeTimestamps, stream);
    }
}





public class ConfigException: UniffiException {
    ConfigException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.
    
    public class External: ConfigException {
        public External(string message): base(message) {}
    }
    
    public class LoggingInitFailed: ConfigException {
        public LoggingInitFailed(string message): base(message) {}
    }
    
}

class FfiConverterTypeConfigError : FfiConverterRustBuffer<ConfigException>, CallStatusErrorHandler<ConfigException> {
    public static FfiConverterTypeConfigError INSTANCE = new FfiConverterTypeConfigError();

    public override ConfigException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new ConfigException.External(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new ConfigException.LoggingInitFailed(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeConfigError.Read()", value));
        }
    }

    public override int AllocationSize(ConfigException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(ConfigException value, BigEndianStream stream) {
        switch (value) {
            case ConfigException.External:
                stream.WriteInt(1);
                break;
            case ConfigException.LoggingInitFailed:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeConfigError.Write()", value));
        }
    }
}





public class FileException: UniffiException {
    FileException(string message): base(message) {}

    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.
    
    public class Io: FileException {
        public Io(string message): base(message) {}
    }
    
    public class External: FileException {
        public External(string message): base(message) {}
    }
    
    public class AppDirectoryCreationFailed: FileException {
        public AppDirectoryCreationFailed(string message): base(message) {}
    }
    
    public class AppNameAlreadySet: FileException {
        public AppNameAlreadySet(string message): base(message) {}
    }
    
    public class DataDirAlreadySet: FileException {
        public DataDirAlreadySet(string message): base(message) {}
    }
    
}

class FfiConverterTypeFileError : FfiConverterRustBuffer<FileException>, CallStatusErrorHandler<FileException> {
    public static FfiConverterTypeFileError INSTANCE = new FfiConverterTypeFileError();

    public override FileException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1: return new FileException.Io(FfiConverterString.INSTANCE.Read(stream));
            case 2: return new FileException.External(FfiConverterString.INSTANCE.Read(stream));
            case 3: return new FileException.AppDirectoryCreationFailed(FfiConverterString.INSTANCE.Read(stream));
            case 4: return new FileException.AppNameAlreadySet(FfiConverterString.INSTANCE.Read(stream));
            case 5: return new FileException.DataDirAlreadySet(FfiConverterString.INSTANCE.Read(stream));
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeFileError.Read()", value));
        }
    }

    public override int AllocationSize(FileException value) {
        return 4 + FfiConverterString.INSTANCE.AllocationSize(value.Message);
    }

    public override void Write(FileException value, BigEndianStream stream) {
        switch (value) {
            case FileException.Io:
                stream.WriteInt(1);
                break;
            case FileException.External:
                stream.WriteInt(2);
                break;
            case FileException.AppDirectoryCreationFailed:
                stream.WriteInt(3);
                break;
            case FileException.AppNameAlreadySet:
                stream.WriteInt(4);
                break;
            case FileException.DataDirAlreadySet:
                stream.WriteInt(5);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeFileError.Write()", value));
        }
    }
}




class FfiConverterOptionalString: FfiConverterRustBuffer<string?> {
    public static FfiConverterOptionalString INSTANCE = new FfiConverterOptionalString();

    public override string? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(string? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterString.INSTANCE.AllocationSize((string)value);
        }
    }

    public override void Write(string? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterString.INSTANCE.Write((string)value, stream);
        }
    }
}




class FfiConverterDictionaryStringString: FfiConverterRustBuffer<Dictionary<string, string>> {
    public static FfiConverterDictionaryStringString INSTANCE = new FfiConverterDictionaryStringString();

    public override Dictionary<string, string> Read(BigEndianStream stream) {
        var len = stream.ReadInt();
        var result = new Dictionary<string, string>(len);
        var readerKey = FfiConverterString.INSTANCE.Read;
        var readerValue = FfiConverterString.INSTANCE.Read;
        for (int i = 0; i < len; i++) {
            var key = readerKey(stream);
            var value = readerValue(stream);
            result[key] = value;
        }

        return result;
    }

    public override int AllocationSize(Dictionary<string, string> value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationKeySizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var allocationKValueSizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationKeySizeFn(item.Key) + allocationKValueSizeFn(item.Value));
        return sizeForLength + sizeForItems;
    }

    public override void Write(Dictionary<string, string> value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Count);
        var writerKey = FfiConverterString.INSTANCE.Write;
        var writerValue = FfiConverterString.INSTANCE.Write;
        foreach (var item in value) {
            writerKey(item.Key, stream);
            writerValue(item.Value, stream);
        }
    }
}



class ConcurrentHandleMap<T> where T: notnull {
    Dictionary<ulong, T> map = new Dictionary<ulong, T>();

    Object lock_ = new Object();
    ulong currentHandle = 0;

    public ulong Insert(T obj) {
        lock (lock_) {
            currentHandle += 1;
            map[currentHandle] = obj;
            return currentHandle;
        }
    }

    public bool TryGet(ulong handle, out T result) {
        lock (lock_) {
            #pragma warning disable 8601 // Possible null reference assignment
            return map.TryGetValue(handle, out result);
            #pragma warning restore 8601
        }
    }

    public T Get(ulong handle) {
        if (TryGet(handle, out var result)) {
            return result;
        } else {
            throw new InternalException("ConcurrentHandleMap: Invalid handle");
        }
    }

    public bool Remove(ulong handle) {
        return Remove(handle, out T result);
    }

    public bool Remove(ulong handle, out T result) {
        lock (lock_) {
            // Possible null reference assignment
            #pragma warning disable 8601
            if (map.TryGetValue(handle, out result)) {
            #pragma warning restore 8601
                map.Remove(handle);
                return true;
            } else {
                return false;
            }
        }
    }
}

[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
delegate void UniFfiFutureCallback(IntPtr continuationHandle, byte pollResult);

internal static class _UniFFIAsync {
    internal const byte UNIFFI_RUST_FUTURE_POLL_READY = 0;
    // internal const byte UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1;

    internal static ConcurrentHandleMap<TaskCompletionSource<byte>> _async_handle_map = new ConcurrentHandleMap<TaskCompletionSource<byte>>();
    public static ConcurrentHandleMap<CancellationTokenSource> _foreign_futures_map = new ConcurrentHandleMap<CancellationTokenSource>();

    // FFI type for Rust future continuations
    internal class UniffiRustFutureContinuationCallback
    {
        public static UniFfiFutureCallback callback = Callback;

        public static void Callback(IntPtr continuationHandle, byte pollResult)
        {
            if (_async_handle_map.Remove((ulong)continuationHandle.ToInt64(), out TaskCompletionSource<byte> task))
            {
                task.SetResult(pollResult);
            }
            else 
            {
                throw new InternalException($"Unable to find continuation handle: {continuationHandle}");
            }
        }
    }

    public class UniffiForeignFutureFreeCallback
    {
        public static _UniFFILib.UniffiForeignFutureFree callback = Callback;

        public static void Callback(ulong handle)
        {
            if (_foreign_futures_map.Remove(handle, out CancellationTokenSource task))
            {
                task.Cancel();
            }
            else
            {
                throw new InternalException($"Unable to find cancellation token: {handle}");
            }
        }
    }

    public delegate F CompleteFuncDelegate<F>(IntPtr ptr, ref UniffiRustCallStatus status);

    public delegate void CompleteActionDelegate(IntPtr ptr, ref UniffiRustCallStatus status);

    private static async Task PollFuture(IntPtr rustFuture, Action<IntPtr, IntPtr, IntPtr> pollFunc)
    {
        byte pollResult;
        do 
        {
            var tcs = new TaskCompletionSource<byte>(TaskCreationOptions.RunContinuationsAsynchronously);
            IntPtr callback = Marshal.GetFunctionPointerForDelegate(UniffiRustFutureContinuationCallback.callback);
            ulong mapEntry = _async_handle_map.Insert(tcs);
            pollFunc(rustFuture, callback, (IntPtr)mapEntry);
            pollResult = await tcs.Task;
        }
        while(pollResult != UNIFFI_RUST_FUTURE_POLL_READY);
    }

    public static async Task<T> UniffiRustCallAsync<T, F, E>(
        IntPtr rustFuture,
        Action<IntPtr, IntPtr, IntPtr> pollFunc,
        CompleteFuncDelegate<F> completeFunc,
        Action<IntPtr> freeFunc,
        Func<F, T> liftFunc,
        CallStatusErrorHandler<E> errorHandler
    ) where E : UniffiException
    {
        try {
            await PollFuture(rustFuture, pollFunc);
            var result = _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => completeFunc(rustFuture, ref status));
            return liftFunc(result);
        }
        finally
        {
            freeFunc(rustFuture);
        }
    }

    public static async Task UniffiRustCallAsync<E>(
        IntPtr rustFuture,
        Action<IntPtr, IntPtr, IntPtr> pollFunc,
        CompleteActionDelegate completeFunc,
        Action<IntPtr> freeFunc,
        CallStatusErrorHandler<E> errorHandler
    ) where E : UniffiException
    {
         try {
            await PollFuture(rustFuture, pollFunc);
            _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => completeFunc(rustFuture, ref status));

        }
        finally
        {
            freeFunc(rustFuture);
        }
    }
}
#pragma warning restore 8625
public static class BaadCoreMethods {
    /// <exception cref="FileException"></exception>
   public static async Task ClearAll(string @dir) 
   {await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        _UniFFILib.uniffi_baad_core_fn_func_clear_all(FfiConverterString.INSTANCE.Lower(@dir)),
        // Poll
        (IntPtr future, IntPtr continuation, IntPtr data) => _UniFFILib.ffi_baad_core_rust_future_poll_void(future, continuation, data),
        // Complete
        (IntPtr future, ref UniffiRustCallStatus status) => {_UniFFILib.ffi_baad_core_rust_future_complete_void(future, ref status);
        },
        // Free
        (IntPtr future) => _UniFFILib.ffi_baad_core_rust_future_free_void(future),
        // Error
        FfiConverterTypeFileError.INSTANCE
    );
   }
    /// <exception cref="FileException"></exception>
   public static async Task CreateParentDir(string @path) 
   {await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        _UniFFILib.uniffi_baad_core_fn_func_create_parent_dir(FfiConverterString.INSTANCE.Lower(@path)),
        // Poll
        (IntPtr future, IntPtr continuation, IntPtr data) => _UniFFILib.ffi_baad_core_rust_future_poll_void(future, continuation, data),
        // Complete
        (IntPtr future, ref UniffiRustCallStatus status) => {_UniFFILib.ffi_baad_core_rust_future_complete_void(future, ref status);
        },
        // Free
        (IntPtr future) => _UniFFILib.ffi_baad_core_rust_future_free_void(future),
        // Error
        FfiConverterTypeFileError.INSTANCE
    );
   }
    /// <exception cref="FileException"></exception>
    public static string DataDir() {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeFileError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_data_dir( ref _status)
));
    }


    /// <exception cref="FileException"></exception>
    public static string GetDataPath(string @filename) {
        return FfiConverterString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeFileError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_get_data_path(FfiConverterString.INSTANCE.Lower(@filename), ref _status)
));
    }


    public static FeatureConfig GetFeatureConfig() {
        return FfiConverterTypeFeatureConfig.INSTANCE.Lift(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_get_feature_config( ref _status)
));
    }


    /// <exception cref="FileException"></exception>
   public static async Task<string> GetOutputDir(string? @path) 
   {
    return await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        _UniFFILib.uniffi_baad_core_fn_func_get_output_dir(FfiConverterOptionalString.INSTANCE.Lower(@path)),
        // Poll
        (IntPtr future, IntPtr continuation, IntPtr data) => _UniFFILib.ffi_baad_core_rust_future_poll_rust_buffer(future, continuation, data),
        // Complete
        (IntPtr future, ref UniffiRustCallStatus status) => {
            return _UniFFILib.ffi_baad_core_rust_future_complete_rust_buffer(future, ref status);
        },
        // Free
        (IntPtr future) => _UniFFILib.ffi_baad_core_rust_future_free_rust_buffer(future),
        // Lift
        (result) => FfiConverterString.INSTANCE.Lift(result),
        // Error
        FfiConverterTypeFileError.INSTANCE
    );
   }
    /// <exception cref="ConfigException"></exception>
    public static void InitLogging(LoggingConfig @config) {
        
    _UniffiHelpers.RustCallWithError(FfiConverterTypeConfigError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_init_logging(FfiConverterTypeLoggingConfig.INSTANCE.Lower(@config), ref _status)
);
    }


    /// <exception cref="ConfigException"></exception>
    public static void InitLoggingDefault() {
        
    _UniffiHelpers.RustCallWithError(FfiConverterTypeConfigError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_init_logging_default( ref _status)
);
    }


    /// <exception cref="FileException"></exception>
   public static async Task<bool> IsDirEmpty(string @path) 
   {
    return await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        _UniFFILib.uniffi_baad_core_fn_func_is_dir_empty(FfiConverterString.INSTANCE.Lower(@path)),
        // Poll
        (IntPtr future, IntPtr continuation, IntPtr data) => _UniFFILib.ffi_baad_core_rust_future_poll_i8(future, continuation, data),
        // Complete
        (IntPtr future, ref UniffiRustCallStatus status) => {
            return _UniFFILib.ffi_baad_core_rust_future_complete_i8(future, ref status);
        },
        // Free
        (IntPtr future) => _UniFFILib.ffi_baad_core_rust_future_free_i8(future),
        // Lift
        (result) => FfiConverterBoolean.INSTANCE.Lift(result),
        // Error
        FfiConverterTypeFileError.INSTANCE
    );
   }
    /// <exception cref="FileException"></exception>
   public static async Task<byte[]> LoadFile(string @path) 
   {
    return await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        _UniFFILib.uniffi_baad_core_fn_func_load_file(FfiConverterString.INSTANCE.Lower(@path)),
        // Poll
        (IntPtr future, IntPtr continuation, IntPtr data) => _UniFFILib.ffi_baad_core_rust_future_poll_rust_buffer(future, continuation, data),
        // Complete
        (IntPtr future, ref UniffiRustCallStatus status) => {
            return _UniFFILib.ffi_baad_core_rust_future_complete_rust_buffer(future, ref status);
        },
        // Free
        (IntPtr future) => _UniFFILib.ffi_baad_core_rust_future_free_rust_buffer(future),
        // Lift
        (result) => FfiConverterByteArray.INSTANCE.Lift(result),
        // Error
        FfiConverterTypeFileError.INSTANCE
    );
   }
    public static void LogDebug(string @message) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_debug(FfiConverterString.INSTANCE.Lower(@message), ref _status)
);
    }


    public static void LogDebugWithField(string @message, string @fieldName, string @fieldValue) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_debug_with_field(FfiConverterString.INSTANCE.Lower(@message), FfiConverterString.INSTANCE.Lower(@fieldName), FfiConverterString.INSTANCE.Lower(@fieldValue), ref _status)
);
    }


    public static void LogDebugWithFields(string @message, Dictionary<string, string> @fields) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_debug_with_fields(FfiConverterString.INSTANCE.Lower(@message), FfiConverterDictionaryStringString.INSTANCE.Lower(@fields), ref _status)
);
    }


    public static void LogError(string @message) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_error(FfiConverterString.INSTANCE.Lower(@message), ref _status)
);
    }


    public static void LogErrorFromString(string @errorMessage) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_error_from_string(FfiConverterString.INSTANCE.Lower(@errorMessage), ref _status)
);
    }


    public static void LogErrorWithField(string @message, string @fieldName, string @fieldValue) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_error_with_field(FfiConverterString.INSTANCE.Lower(@message), FfiConverterString.INSTANCE.Lower(@fieldName), FfiConverterString.INSTANCE.Lower(@fieldValue), ref _status)
);
    }


    public static void LogErrorWithFields(string @message, Dictionary<string, string> @fields) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_error_with_fields(FfiConverterString.INSTANCE.Lower(@message), FfiConverterDictionaryStringString.INSTANCE.Lower(@fields), ref _status)
);
    }


    public static void LogInfo(string @message) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_info(FfiConverterString.INSTANCE.Lower(@message), ref _status)
);
    }


    public static void LogInfoWithField(string @message, string @fieldName, string @fieldValue) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_info_with_field(FfiConverterString.INSTANCE.Lower(@message), FfiConverterString.INSTANCE.Lower(@fieldName), FfiConverterString.INSTANCE.Lower(@fieldValue), ref _status)
);
    }


    public static void LogInfoWithFields(string @message, Dictionary<string, string> @fields) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_info_with_fields(FfiConverterString.INSTANCE.Lower(@message), FfiConverterDictionaryStringString.INSTANCE.Lower(@fields), ref _status)
);
    }


    public static void LogRecoverableErrorFromString(string @errorMessage, string @recoveryAction) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_recoverable_error_from_string(FfiConverterString.INSTANCE.Lower(@errorMessage), FfiConverterString.INSTANCE.Lower(@recoveryAction), ref _status)
);
    }


    public static void LogTrace(string @message) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_trace(FfiConverterString.INSTANCE.Lower(@message), ref _status)
);
    }


    public static void LogTraceWithField(string @message, string @fieldName, string @fieldValue) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_trace_with_field(FfiConverterString.INSTANCE.Lower(@message), FfiConverterString.INSTANCE.Lower(@fieldName), FfiConverterString.INSTANCE.Lower(@fieldValue), ref _status)
);
    }


    public static void LogTraceWithFields(string @message, Dictionary<string, string> @fields) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_trace_with_fields(FfiConverterString.INSTANCE.Lower(@message), FfiConverterDictionaryStringString.INSTANCE.Lower(@fields), ref _status)
);
    }


    public static void LogWarn(string @message) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_warn(FfiConverterString.INSTANCE.Lower(@message), ref _status)
);
    }


    public static void LogWarnWithField(string @message, string @fieldName, string @fieldValue) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_warn_with_field(FfiConverterString.INSTANCE.Lower(@message), FfiConverterString.INSTANCE.Lower(@fieldName), FfiConverterString.INSTANCE.Lower(@fieldValue), ref _status)
);
    }


    public static void LogWarnWithFields(string @message, Dictionary<string, string> @fields) {
        
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_log_warn_with_fields(FfiConverterString.INSTANCE.Lower(@message), FfiConverterDictionaryStringString.INSTANCE.Lower(@fields), ref _status)
);
    }


    /// <exception cref="FileException"></exception>
   public static async Task SaveFile(string @path, byte[] @content) 
   {await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        _UniFFILib.uniffi_baad_core_fn_func_save_file(FfiConverterString.INSTANCE.Lower(@path), FfiConverterByteArray.INSTANCE.Lower(@content)),
        // Poll
        (IntPtr future, IntPtr continuation, IntPtr data) => _UniFFILib.ffi_baad_core_rust_future_poll_void(future, continuation, data),
        // Complete
        (IntPtr future, ref UniffiRustCallStatus status) => {_UniFFILib.ffi_baad_core_rust_future_complete_void(future, ref status);
        },
        // Free
        (IntPtr future) => _UniFFILib.ffi_baad_core_rust_future_free_void(future),
        // Error
        FfiConverterTypeFileError.INSTANCE
    );
   }
    /// <exception cref="FileException"></exception>
    public static void SetAppName(string @name) {
        
    _UniffiHelpers.RustCallWithError(FfiConverterTypeFileError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_set_app_name(FfiConverterString.INSTANCE.Lower(@name), ref _status)
);
    }


    /// <exception cref="FileException"></exception>
    public static void SetDataDir(string @path) {
        
    _UniffiHelpers.RustCallWithError(FfiConverterTypeFileError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_baad_core_fn_func_set_data_dir(FfiConverterString.INSTANCE.Lower(@path), ref _status)
);
    }


}

